# Generated by Django 5.2.3 on 2025-06-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mobile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=20)),
                ("brand", models.CharField(max_length=20)),
                ("description", models.CharField(default="No Description")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
